apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: olympis-ingress
  annotations:
    networking.gke.io/managed-certificates: "olympis-gke-cert"
spec:
  ingressClassName: "gce"
  rules:
    - host: gke.olympisai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: olympis-server
                port:
                  number: 8000
