apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml
  - managed-cert.yaml
  - priorities.yaml

patches:
  - path: patch-config.yaml
  - path: patch-deployment.yaml
  - path: patch-workers.yaml
  - path: patch-redis.yaml
  - path: patch-keda.yaml

