apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml
  - managed-cert.yaml

patches:
  - path: patch-config.yaml
  - path: patch-deployment.yaml

