apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-core
value: 1000000
globalDefault: false
description: "For API and Redis"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority-worker
value: 1000
globalDefault: false
description: "For Crawlers/AI"
