[project]
name = "olympis-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic[email]>=2.11.9",
    "pydantic-ai>=1.0.14",
    "rq>=2.6.0",
]
