apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - cluster-issuer.yaml

patches:
  - path: patch-config.yaml
  - path: patch-service.yaml

  - path: patch-deployment.yaml
  - path: patch-workers.yaml
