apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rq-worker-scaler
spec:
  maxReplicaCount: 2
  minReplicaCount: 1

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: agents-worker-scaler
spec:
  maxReplicaCount: 4
  minReplicaCount: 1

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: crawler-worker-scaler
spec:
  maxReplicaCount: 4
  minReplicaCount: 1
