apiVersion: v1
kind: ConfigMap
metadata:
  name: olympis-config
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_SERVER: "10.44.96.3"
---
apiVersion: v1
kind: Secret
metadata:
  name: olympis-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Databaseadmin1@"
