apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rq-worker-scaler
spec:
  scaleTargetRef:
    name: rq-worker
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 2
  cooldownPeriod: 30
  triggers:
    - type: redis
      metadata:
        address: redis-stack.default.svc.cluster.local:6379
        listName: rq:queue:default
        listLength: "5"

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: agents-worker-scaler
spec:
  scaleTargetRef:
    name: agents-worker
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 2
  cooldownPeriod: 30
  triggers:
    - type: redis
      metadata:
        address: redis-stack.default.svc.cluster.local:6379
        listName: rq:queue:agents
        listLength: "5"

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: crawler-worker-scaler
spec:
  scaleTargetRef:
    name: crawler-worker
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 2
  cooldownPeriod: 30
  triggers:
    - type: redis
      metadata:
        address: redis-stack.default.svc.cluster.local:6379
        listName: rq:queue:crawler
        listLength: "5"
